project:
  type: website
  output-dir: docs

website:
  title: "Bianca Berron"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Surfing.qmd
      - coding_progress.qmd
    page-footer:
      background: light
      left: Copyright 2023, Bianca Berron
      right:
        icon: github
        href: https://github.com/bianca-berron

format:
  html:
    theme: sandstone
    mainfont: Playfair
    css: styles.css
    toc: true
    page-layout: full

editor: visual

